### ISSUE TITLE
Add S3 connection profiles for OVH Public Cloud Storage

### ISSUE THREAD

**Issue by dkocher** [iterate-ch/profiles#26]
Existing profile using OpenStack Swift [^1].

[^1]: https://github.com/iterate-ch/profiles/blob/1a219ccff4d830c536d8004023f309ad49fd9853/OVH%20Public%20Cloud%20Storage.cyberduckprofile

**Comment by AliveDevil** [comment]
https://help-beta.ovhcloud.com/csm/de-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047388

**Comment by dkocher** [comment]
Endpoints are documented in Endpoints and Object Storage Geoavailability [^1]

[^1]: https://support.us.ovhcloud.com/hc/en-us/articles/10667991081107-Endpoints-and-Object-Storage-Geoavailability

**Comment by dkocher** [comment]
Available regions

- Gravelines: gra
- Strasbourg: sbg
- Beauharnois: bhs
- Roubaix: rbx

**Comment by AliveDevil** [comment]
OVH support make any sense to me.

The support.us-site refers to us-east-va, while both the help-beta as well as their docs[^1] only mention europe based endpoints.
[^1]: https://docs.ovh.com/us/en/storage/object-storage/s3/location/

**Comment by dkocher** [comment]
Could probably create profiles for both

* Standard Object Storage - S3 API
> The perfect storage solution for high volumes of data at the best price. A wide range of S3 APIs are available with this solution.

* High Performance Object Storage - S3 API

> A solution adapted to the most resource-intensive needs, which require high read and write speeds along with storage.
