### ISSUE TITLE
Add connection profile for Swisscom S3 Dynamic Storage

### ISSUE THREAD

**Issue by dkocher** [iterate-ch/profiles#84]
> https://docs.developer.swisscom.com/service-offerings/dynamic-storage.html#endpoints

**Comment by dkocher** [comment]
Opened [^1] for clarifications.

[^1]: swisscom/docs-appcloud-service-offerings#111

**Comment by rdkayman** [comment]
Perfect, this will help a lot, thank you.

**Comment by dkocher** [comment]
I have amended the profile configuration to disable the prompt to select a region when creating a bucket in 9491daf5.
